spring.application.name=book-club-planner
google.books.api.key=AIzaSyAGQ-Tb6D3xh8poaJWLdhu7rp0Rgh6XKFo
google.books.base-url=https://www.googleapis.com/books/v1/volumes

spring.datasource.url=jdbc:postgresql://localhost:5432/reading_club_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true